[package]
name = "phys_calc_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "2.6.0"
proc-macro2 = "1.0.87"
quote = "1.0.37"
syn = { version = "2.0.79", features = ["derive"] }

[lib]
proc-macro = true


